package com.sphereex.cases.transaction.shardingjdbc;

import com.sphereex.cases.ShardingJdbcBaseTest;
import com.sphereex.core.AutoTest;
import com.sphereex.core.CaseInfo;
import org.apache.shardingsphere.driver.jdbc.core.connection.ShardingSphereConnection;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Collection;
import java.util.Collections;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

@AutoTest
public class ShardingJdbcStatementExecuteTest extends ShardingJdbcBaseTest {
    
    public ShardingJdbcStatementExecuteTest() {
        CaseInfo caseInfo = new CaseInfo();
        caseInfo.setName("ShardingJdbcStatementExecuteTest");
        caseInfo.setFeature("transaction");
        caseInfo.setTag("jdbc");
        caseInfo.setStatus(false);
        setCaseInfo(caseInfo);
    }
    
    @Override
    public void pre() throws Exception {
        super.pre();
        Connection conn = getDataSource().getConnection();
        Statement statement = conn.createStatement();
        statement.execute("delete from account;");
        statement.execute("insert into account(id, balance, transaction_id) values(1,1,1);");
        conn.close();
    }
    
    @Override
    public void run() throws SQLException {
        executeWithOnlySql();
        executeWithSqlAndAutoGeneratedKeys();
//        executeWithSqlAndColumnIndexes();
        executeWithSqlAndColumnNames();
    }
    
    private void executeWithOnlySql() throws SQLException {
        ShardingSphereConnection conn = (ShardingSphereConnection) getDataSource().getConnection();
        conn.setAutoCommit(false);
        assertFalse(conn.getConnectionManager().getConnectionTransaction().isRollbackOnly());
        Statement statement1 = conn.createStatement();
        statement1.executeQuery("select * from account;");
        Statement statement2 = conn.createStatement();
        Statement statement3 = conn.createStatement();
        try {
            statement2.execute("update account set balance=100 where id=1;");
            statement3.execute("update account1 set balance=100 where id=1;");
            throw new SQLException("expect report SQLException, but not report");
        } catch (SQLException ex) {
            assertTrue(conn.getConnectionManager().getConnectionTransaction().isRollbackOnly());
        }
        conn.commit();
        Statement statement4 = conn.createStatement();
        ResultSet r = statement4.executeQuery("select * from account;");
        if (r.next()) {
            int balance = r.getInt("balance");
            assertTrue(balance == 1);
        } else {
            throw new SQLException("expect one recode, but not.");
        }
    }
    
    private void executeWithSqlAndAutoGeneratedKeys() throws SQLException {
        ShardingSphereConnection conn = (ShardingSphereConnection) getDataSource().getConnection();
        conn.setAutoCommit(false);
        assertFalse(conn.getConnectionManager().getConnectionTransaction().isRollbackOnly());
        Statement statement1 = conn.createStatement();
        statement1.executeQuery("select * from account;");
        Statement statement2 = conn.createStatement();
        Statement statement3 = conn.createStatement();
        try {
            statement2.execute("update account set balance=100 where id=1;");
            statement3.execute("update account1 set balance=100 where id=1;", 1);
            throw new SQLException("expect report SQLException, but not report");
        } catch (SQLException ex) {
            assertTrue(conn.getConnectionManager().getConnectionTransaction().isRollbackOnly());
        }
        conn.commit();
        Statement statement4 = conn.createStatement();
        ResultSet r = statement4.executeQuery("select * from account;");
        if (r.next()) {
            int balance = r.getInt("balance");
            assertTrue(balance == 1);
        } else {
            throw new SQLException("expect one recode, but not.");
        }
    }
    
    private void executeWithSqlAndColumnIndexes() throws SQLException {
        ShardingSphereConnection conn = (ShardingSphereConnection) getDataSource().getConnection();
        conn.setAutoCommit(false);
        assertFalse(conn.getConnectionManager().getConnectionTransaction().isRollbackOnly());
        Statement statement1 = conn.createStatement();
        statement1.executeQuery("select * from account;");
        Statement statement2 = conn.createStatement();
        Statement statement3 = conn.createStatement();
        try {
            statement2.execute("update account set balance=100 where id=1;");
            statement3.execute("update account1 set balance=100 where id=1;", new int[]{2});
            throw new SQLException("expect report SQLException, but not report");
        } catch (SQLException ex) {
            assertTrue(conn.getConnectionManager().getConnectionTransaction().isRollbackOnly());
        }
        conn.commit();
        Statement statement4 = conn.createStatement();
        ResultSet r = statement4.executeQuery("select * from account;");
        if (r.next()) {
            int balance = r.getInt("balance");
            assertTrue(balance == 1);
        } else {
            throw new SQLException("expect one recode, but not.");
        }
    }
    
    private void executeWithSqlAndColumnNames() throws SQLException {
        ShardingSphereConnection conn = (ShardingSphereConnection) getDataSource().getConnection();
        conn.setAutoCommit(false);
        assertFalse(conn.getConnectionManager().getConnectionTransaction().isRollbackOnly());
        Statement statement1 = conn.createStatement();
        statement1.executeQuery("select * from account;");
        Statement statement2 = conn.createStatement();
        Statement statement3 = conn.createStatement();
        try {
            statement2.execute("update account set balance=100 where id=1;");
            statement3.execute("update account1 set balance=100 where id=1;", new String[]{"balance"});
            throw new SQLException("expect report SQLException, but not report");
        } catch (SQLException ex) {
            assertTrue(conn.getConnectionManager().getConnectionTransaction().isRollbackOnly());
        }
        conn.commit();
        Statement statement4 = conn.createStatement();
        ResultSet r = statement4.executeQuery("select * from account;");
        if (r.next()) {
            int balance = r.getInt("balance");
            assertTrue(balance == 1);
        } else {
            throw new SQLException("expect one recode, but not.");
        }
    }
}
